### ISSUE TITLE
Should null be included in EntityFieldValue union type?

### ISSUE THREAD

**Issue by Jontem** [dividab/graphql-norm#2]
Should `null` be included in `EntityFieldValue` union type? Null is a valid graphql return type.

It's included in the entity map type as valid but not in `EntityFieldValue`

```typescript

export type EntityId = string;

export type EntityFieldValue =
  | EntityId
  | string
  | boolean
  | number
  | EntityFieldValueArray;

export interface EntityFieldValueArray
  extends ReadonlyArray<EntityFieldValue> {}

export interface Entity {
  readonly [field: string]: null | EntityFieldValue;
}

```

**Comment by jonaskello** [comment]
`null` could be included in `EntityFieldValue`, or external users could specify the type as `EntityFieldValue | null`. If `null` is included then the trade-off is that you can no longer specify that a `EntityFieldValue` is not nullable. Of course, with newer versions of typescript I think you can do `NotNull<EntityFieldValue>` to remove `null` from the type so this might be a reasonable trade-off.

**Comment by jonaskello** [comment]
@Jontem perhaps you can research if including null is the best way forward and if so make a PR for it. Also it would be nice to know if `NotNull<EntityFieldValue>` would actually work.

**Comment by Jontem** [comment]
> If null is included then the trade-off is that you can no longer specify that a EntityFieldValue is not nullable

If something should be done with the value you still have to do some typechecking because `EntityFieldValue` could be a number of different types?

I'm not arguing for any specific option here just trying to bring all pros and cons

**Comment by Jontem** [comment]
> @Jontem perhaps you can research if including null is the best way forward and if so make a PR for it. Also it would be nice to know if NotNull<EntityFieldValue> would actually work.

Typescript has the built in `NonNullable<T>`. A non nullable map can be done via

```typescript
type NonNull<T> = { [P in keyof T]: NonNullable<T> };
```

**Comment by jonaskello** [comment]
Ok, and even simpler I think you could do something like this:

```ts
type NonNullEntityFiledValue = NonNullable<EntityFieldValue>
```

So if `EntityFieldValue` was changed to include `null` then `NonNullEntityFiledValue` would be the same as before the change.

**Comment by Jontem** [comment]
My vacation brain has forgotten what the root cause was to this.

I made a pull request #6 to work with. 

How should we handle the nested array?

**Comment by jonaskello** [comment]
I think null has been added [here](https://github.com/dividab/graphql-norm/blob/8d47c8527b49991fe9db2f13eabbae8e3b86d2d2/src/norm-map.ts#L12). If this is still an issue please reopen.
