### ISSUE TITLE
Is this abandoned? Why?

### ISSUE THREAD

**Issue by frederikhors** [dividab/graphql-norm#63]
Is this abandoned? Why?

**Comment by jonaskello** [comment]
We still actively use this package in a few projects. I guess the reason why we have not updated it in a while is that it does one thing and does it well enough :-). Do you miss any functionality?

**Comment by frederikhors** [comment]
> Do you miss any functionality?

Nope. I was planning to use it, but I was scared about lack of interest from you.

Thanks for the answer!
